<a href="https://colab.research.google.com/github/kdemertzis/EKPA/blob/main/Diabetes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [29]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
data = pd.read_csv('https://raw.githubusercontent.com/TK-Konstantinos/Kiosses.Diabetes/main/phishing_dataset.csv', delimiter=',')

In [25]:
data = pd.read_csv('https://raw.githubusercontent.com/TK-Konstantinos/Kiosses.Diabetes/main/phishing_dataset.csv', delimiter=',')
data.head()

Domain  Have_IP  Have_At  URL_Length  URL_Depth  Redirection  \
0  graphicriver.net        0        0           1          1            0   
1         ecnavi.jp        0        0           1          1            1   
2      hubpages.com        0        0           1          1            0   
3   extratorrent.cc        0        0           1          3            0   
4     icicibank.com        0        0           1          3            0   

   https_Domain  TinyURL  Prefix/Suffix  DNS_Record  Web_Traffic  Domain_Age  \
0             0        0              0           0            1           1   
1             0        0              0           0            1           1   
2             0        0              0           0            1           0   
3             0        0              0           0            1           0   
4             0        0              0           0            1           0   

   Domain_End  iFrame  Mouse_Over  Right_Click  Web_Forwards  Label  
0           1       0           0            1             0      0  
1           1       0           0            1             0      0  
2           1       0           0            1             0      0  
3           1       0           0            1             0      0  
4           1       0           0            1             0      0

In [26]:
data = data.drop(['Domain', 'Label'], axis=1)

In [27]:
print(data.head())

   Have_IP  Have_At  URL_Length  URL_Depth  Redirection  https_Domain  \
0        0        0           1          1            0             0   
1        0        0           1          1            1             0   
2        0        0           1          1            0             0   
3        0        0           1          3            0             0   
4        0        0           1          3            0             0   

   TinyURL  Prefix/Suffix  DNS_Record  Web_Traffic  Domain_Age  Domain_End  \
0        0              0           0            1           1           1   
1        0              0           0            1           1           1   
2        0              0           0            1           0           1   
3        0              0           0            1           0           1   
4        0              0           0            1           0           1   

   iFrame  Mouse_Over  Right_Click  Web_Forwards  
0       0           0            1       

In [ ]:
print(data.isnull().sum())
data = data.dropna()

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state=43)

In [ ]:
# Standardize the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
# Define classifiers
classifiers = [
    LogisticRegression(),
    SVC(),
    RandomForestClassifier(),
    MLPClassifier(),
    KNeighborsClassifier(),
    DecisionTreeClassifier()
]

In [ ]:
# Evaluate and compare classifiers
results = {'Classifier': [], 'Accuracy': [], 'Precision': [], 'Recall': [], 'F1 Score': []}

for clf in classifiers:
    clf_name = clf.__class__.__name__

    # Train the classifier
    clf.fit(X_train, y_train)

    # Make predictions
    y_pred = clf.predict(X_test)

    # Calculate evaluation metrics
    acc = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='weighted')
    recall = recall_score(y_test, y_pred, average='weighted')
    f1 = f1_score(y_test, y_pred, average='weighted')

    # Confusion matrix
    cm = confusion_matrix(y_test, y_pred)

    # Display results
    print(f"\n{clf_name} Metrics:")
    print(f"Accuracy: {acc}")
    print(f"Precision: {precision}")
    print(f"Recall: {recall}")
    print(f"F1 Score: {f1}")
    print("Confusion Matrix:")
    print(cm)

    # Store results for comparison
    results['Classifier'].append(clf_name)
    results['Accuracy'].append(acc)
    results['Precision'].append(precision)
    results['Recall'].append(recall)
    results['F1 Score'].append(f1)


LogisticRegression Metrics:
Accuracy: 0.7662337662337663
Precision: 0.7604659628685839
Recall: 0.7662337662337663
F1 Score: 0.7617924528301887
Confusion Matrix:
[[132  22]
 [ 32  45]]

SVC Metrics:
Accuracy: 0.7878787878787878
Precision: 0.7824975049900199
Recall: 0.7878787878787878
F1 Score: 0.7823954397825943
Confusion Matrix:
[[136  18]
 [ 31  46]]

RandomForestClassifier Metrics:
Accuracy: 0.7705627705627706
Precision: 0.7672955974842767
Recall: 0.7705627705627706
F1 Score: 0.7685457183495222
Confusion Matrix:
[[130  24]
 [ 29  48]]

MLPClassifier Metrics:
Accuracy: 0.7748917748917749
Precision: 0.7702630166398283
Recall: 0.7748917748917749
F1 Score: 0.7715738974625744
Confusion Matrix:
[[132  22]
 [ 30  47]]

KNeighborsClassifier Metrics:
Accuracy: 0.7316017316017316
Precision: 0.7283394023466851
Recall: 0.7316017316017316
F1 Score: 0.7297435897435898
Confusion Matrix:
[[125  29]
 [ 33  44]]

DecisionTreeClassifier Metrics:
Accuracy: 0.6753246753246753
Precision: 0.68310657596371

/opt/anaconda3/lib/python3.11/site-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


In [ ]:
# Display comparison results
results_df = pd.DataFrame(results)
results_df = results_df.sort_values(by='Accuracy', ascending=False)
print("\nComparison of Classifiers:")
print(results_df)


Comparison of Classifiers:
               Classifier  Accuracy  Precision    Recall  F1 Score
1                     SVC  0.766234   0.762168  0.766234  0.763650
4    KNeighborsClassifier  0.766234   0.764736  0.766234  0.765425
3           MLPClassifier  0.761905   0.761123  0.761905  0.761499
0      LogisticRegression  0.757576   0.751148  0.757576  0.752828
2  RandomForestClassifier  0.740260   0.738576  0.740260  0.739361
5  DecisionTreeClassifier  0.714286   0.714286  0.714286  0.714286
